### ISSUE TITLE
calling this plugin several times

### ISSUE THREAD

**Issue by romaintb** [idottv/mongoose-post-find#2]
Hi,

I don't know exactly where to look for, so I will just explain here, hoping this is not totally off topic.

In one of our use cases, we used the plugin several times on one model. Our problem is that only the last inclusion of the plugin is executed when we do a find/findOne. I think this is the expected behavior, but is there a way to have mutilple find/findOne hooks ? I know I can pass an array of functions to mongoose-post-find, but if I use your plugin in say plugins, I am screwed.

I'll try to put that into code : 

``` javascript
// mymodel.js
var schema = new mongoose.Schema({foo: String});
schema.plugin(plugina);
schema.plugin(pluginb);

// plugin-a.js
var postFind = require('mongoose-post-find');
module.exports = function(schema, options) {
    schema.plugin(postFind, {
        find: function(res, done) {
            //do something
        }
    });
};

// plugin-b.js
var postFind = require('mongoose-post-find');
module.exports = function(schema, options) {
    schema.plugin(postFind, {
        find: function(res, done) {
            //do something else
        }
    });
};
```

With this example, only the B plugin hooks will be called.

I'm sorry if that can't be done, or if the problem is solvable only somewhere in mongoose or whatever, I  just don't know where to go from here.

Thanks !

**Comment by vlavrynovych** [comment]
As I understand current implementation works only with one handler. If it is true it explains such behaviour. B plugin rewrites the A plugin handler. And I think that it is normal.

**Comment by kalmecak** [comment]
May be the problem is, if the code is in the same file, that node is taking the last export you are writing, so you can try something like:

```javascript
// mymodel.js
var schema = new mongoose.Schema({foo: String});
schema.plugin(plugina);
schema.plugin(pluginb);

// plugin-a.js
var postFind = require('mongoose-post-find');
module.exports.pluginA = function(schema, options) {
    // your code ...
};

// plugin-b.js
var postFind = require('mongoose-post-find');
module.exports.pluginB = function(schema, options) {
    // your code
};

// Or may be you can export an object of functions:

var postFind = require('mongoose-post-find');
module.exports = {
   pluginA: function(schema, options) {
       // your code for plugin-a ...
   },
   pluginB: function(schema, options) {
       // your code for plugin-b ...
   }

}
```

**Comment by romaintb** [comment]
(closing as I don't use this anymore)
